---
step-runner-config:
  global-defaults:
    application-name: quarkus-quickstart

  deploy:
  - implementer: ArgoCD
    config:
      deployment-config-repo: http://gitea.tssc.rht-set.com/ploigos-reference-applications/quarkus-quickstart-deployments.git
      git-username: sa-ploigos-ref-apps
